version: '3.7'

services:
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
        - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: piyush
    networks: 
        - stock-network
networks: 
  stock-network: