version: '3.3'

services:
  db:
    image: postgres
    restart: always
    container_name: 'my_postgres'
    environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=piyush
        - POSTGRES_DB=mydb
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '54320:5432'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
        - postgres-data:/var/lib/postgresql/data